export const businessData = [
  {
      category: 'Restaurants',
      icon: "/assets/restaurant.png",
      businesses: [
          {
              id: '1',
              name: 'Tatu Moto',
              rating: 4.5,
              logo: '/assets/tatu-moto.png',
              openingTime: '9am',
              closingTime: '10pm',
              address: 'Roysambu',
              heroImage: '/assets/tatu moto.png',
              reviews: 19,
              products: [
                  { productName: 'Chicken Fry', price: '450/= ', image: '/assets/grilled.png' },
                  { productName: 'Beef Fry', price: '450/= ', image: '/assets/grilled.png' },
                  { productName: 'Fish Fry', price: '450/= ', image: '/assets/grilled.png' },
              ],
          },
          {
              id: '2',
              name: 'Oppo Zone',
              rating: 4.0,
              logo: '/assets/oppo.png',
              openingTime: '7am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/oppo.png',
              reviews: 19,
              products: [
                  { productName: 'Grilled Chicken', price: '500/= ', image: '/assets/grilled.png' },
              ],
          },
          {
              id: '3',
              name: 'Grill Master',
              rating: 4.0,
              logo: '/assets/grill-masters.png',
              openingTime: '7am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/grill masters.png',
              reviews: 19,
              products: [
                  { productName: 'Grilled Chicken', price: '500/= ', image: '/assets/grilled-chicken.png' },
              ],
          },
      ],
  },
  {
      category: 'Barbershop',
      icon: '/assets/barbershop.png',
      businesses: [
          {
              id: '4',
              name: 'Classic Cuts',
              rating: 4.2,
              logo: '/assets/classic-cuts.png',
              openingTime: '8am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/tatu moto.png',
              reviews: 19,
              products: [
                  { productName: 'Haircut', price: '300/= ', image: '/assets/haircut.png' },
                  { productName: 'Beard Trim', price: '150/= ', image: '/assets/beard-trim.png' },
              ],
          },
          {
              id: '5',
              name: 'Gents Grooming',
              rating: 4.3,
              logo: '/assets/gents-grooming.png',
              openingTime: '8am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/tatu moto.png',
              reviews: 19,
              products: [
                  { productName: 'Haircut', price: '350/= ', image: '/assets/haircut-2.png' },
                  { productName: 'Shaving', price: '200/= ', image: '/assets/shaving.png' },
              ],
          },
      ],
  },
  {
      category: 'Shoes',
      icon: "/assets/shoes.png",
      businesses: [
          {
              id: '6',
              name: 'Sneaker World',
              rating: 4.5,
              logo: '/assets/sneaker-world.png',
              openingTime: '8am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/tatu moto.png',
              reviews: 19,
              products: [
                  { productName: 'Running Shoes', price: '3,000/= ', image: '/assets/running-shoes.png' },
                  { productName: 'Casual Sneakers', price: '2,500/= ', image: '/assets/casual-sneakers.png' },
              ],
          },
          {
              id: '7',
              name: 'Footwear Hub',
              rating: 4.1,
              logo: '/assets/footwear-hub.png',
              openingTime: '8am',
              closingTime: '11pm',
              address: 'Roysambu',
              heroImage: '/assets/tatu moto.png',
              reviews: 19,
              products: [
                  { productName: 'Formal Shoes', price: '4,000/= ', image: '/assets/formal-shoes.png' },
                  { productName: 'Sandals', price: '1,500/= ', image: '/assets/sandals.png' },
              ],
          },
      ],
  },
];
